# Site settings
title: Nash Metal Werks
email: nashmetal13@gmail.com
description: Description goes here. > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nashmetal.art" # the base hostname & protocol for your site

twitter_username:
facebook_username: nashmetalwerks
github_username:

# Build settings
markdown: kramdown
